# Унікальний ключ проєкту (вигадай будь-який)
sonar.projectKey=lazy-implement-js
sonar.projectName=Lazy Implement QA

# Шлях до сирців (відносно кореня)
sonar.sources=src
# Шлях до тестів
sonar.tests=tests

# Кодування та мова
sonar.sourceEncoding=UTF-8
sonar.language=js
sonar.javascript.environments=node,browser

# Для Лаби №8: Шлях до звітів про покриття (Coverage)
# Jest генерує їх у папку coverage після команди npm test -- --coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Виключаємо зайве з аналізу (бібліотеки та кеш)
sonar.exclusions=node_modules/**, dist/**, .parcel-cache/**